CREATE TABLE cms.uploads ( Id INT(11) NOT NULL AUTO_INCREMENT ,
  Filename VARCHAR(100) NOT NULL ,
  Filepath VARCHAR(255) NOT NULL ,
  Filesize VARCHAR(50) NOT NULL ,
  Description VARCHAR(255) NOT NULL ,
  pub_date TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ,

  PRIMARY KEY (Id)
  ) 
ENGINE = InnoDB;
